import { mutation } from "./_generated/server";
import { v } from "convex/values";

// Vendor data from the Excel file
const vendorData = [
  {
    "name": "Arman Supply Inc.",
    "email": "armansupplyinc@gmail.com",
    "phone": "(845) 358-6446",
    "address": "381 Route 59",
    "city": "West Nyack",
    "state": "NY",
    "zipCode": "10994",
    "contactPerson": "Lou",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Azores Concrete Pumping LLC",
    "email": "simpac24@aol.com",
    "phone": "(914) 804-9101",
    "address": "852 Franklin Ave.",
    "city": "Franklin Lakes",
    "state": "NJ",
    "zipCode": "7417",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["Concrete", "Ready Mix"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Beckerle Lumber Supply Co Inc",
    "email": "office@beckerlelumber.com",
    "phone": "(845) 359-4633",
    "address": "P.O Box 649 3 Chestnut St",
    "city": "Spring Valley",
    "state": "NY",
    "zipCode": "10977",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["Lumber", "Framing"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Bonded Concrete",
    "email": "ar@bondedconcrete.com",
    "phone": "(518) 273-5800",
    "address": "PO Box 189",
    "city": "Watervliet",
    "state": "NY",
    "zipCode": "12189",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["Concrete", "Ready Mix"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Brewster Transit Mix",
    "email": "Marilyn.tyree@brewstertransitmix.com",
    "phone": "(845) 279-4270",
    "address": "31 Field Lane",
    "city": "Brewster",
    "state": "NY",
    "zipCode": "10509",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["Transportation", "Delivery"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Building Materials Corp. of America",
    "email": "info@bmcamerica.com",
    "phone": "(845) 359-5440",
    "address": "110 Route 59",
    "city": "Suffern",
    "state": "NY",
    "zipCode": "10901",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "C & S Supply Inc",
    "email": "cs-supply@optimum.net",
    "phone": "(845) 359-8100",
    "address": "6 New Hempstead Rd",
    "city": "New City",
    "state": "NY",
    "zipCode": "10956",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Capitol Plumbing Supply",
    "email": "capitolplumbing@aol.com",
    "phone": "(518) 462-4106",
    "address": "1247 Central Ave",
    "city": "Albany",
    "state": "NY",
    "zipCode": "12205",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["Plumbing", "HVAC"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Catskill Building Supply Inc",
    "email": "info@catskillbuildingsupply.com",
    "phone": "(845) 679-4500",
    "address": "3462 Route 28",
    "city": "Shokan",
    "state": "NY",
    "zipCode": "12481",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Central Hudson Gas & Electric Corp",
    "email": "customerservice@cenhud.com",
    "phone": "(845) 452-2000",
    "address": "284 South Ave",
    "city": "Poughkeepsie",
    "state": "NY",
    "zipCode": "12601",
    "contactPerson": "",
    "vendorType": "service",
    "specialties": ["Electrical", "Lighting"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Chester Building Supply",
    "email": "chesterbldgsupply@gmail.com",
    "phone": "(845) 469-2311",
    "address": "1965 Kings Hwy",
    "city": "Chester",
    "state": "NY",
    "zipCode": "10918",
    "contactPerson": "Dick",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Costco Wholesale",
    "email": "memberservices@costco.com",
    "phone": "(845) 623-0100",
    "address": "141 Crooked Hill Rd",
    "city": "Pearl River",
    "state": "NY",
    "zipCode": "10965",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Construction"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "County Materials Corporation",
    "email": "info@countymaterials.com",
    "phone": "(715) 552-4450",
    "address": "PO Box 916",
    "city": "Roberts",
    "state": "WI",
    "zipCode": "54023",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Eagle Materials Inc",
    "email": "info@eaglematerials.com",
    "phone": "(214) 432-2000",
    "address": "3811 Turtle Creek Blvd",
    "city": "Dallas",
    "state": "TX",
    "zipCode": "75219",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Home Depot",
    "email": "customercare@homedepot.com",
    "phone": "(845) 623-8715",
    "address": "240 W Route 59",
    "city": "Nanuet",
    "state": "NY",
    "zipCode": "10954",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Hudson Valley Building Supply",
    "email": "hvbs@hvc.rr.com",
    "phone": "(845) 469-2808",
    "address": "1985 Kings Hwy",
    "city": "Chester",
    "state": "NY",
    "zipCode": "10918",
    "contactPerson": "Rick",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Lowe's Home Improvement",
    "email": "customercare@lowes.com",
    "phone": "(845) 623-0905",
    "address": "250 W Route 59",
    "city": "Nanuet",
    "state": "NY",
    "zipCode": "10954",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Marcal Manufacturing LLC",
    "email": "info@marcalllc.com",
    "phone": "(201) 225-5700",
    "address": "1 Market St",
    "city": "Elmwood Park",
    "state": "NJ",
    "zipCode": "7407",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Construction"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Mid Hudson Pattern Works Inc",
    "email": "info@midhudsonpattern.com",
    "phone": "(845) 255-7123",
    "address": "3 Paradies Ln",
    "city": "New Paltz",
    "state": "NY",
    "zipCode": "12561",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Construction"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Orange County Choppers",
    "email": "info@orangecountychoppers.com",
    "phone": "(845) 294-3733",
    "address": "14 Crossroads Ct",
    "city": "Newburgh",
    "state": "NY",
    "zipCode": "12550",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Construction"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Perkins Restaurant & Bakery",
    "email": "guestrelations@perkinsrestaurants.com",
    "phone": "(845) 353-5160",
    "address": "106 Route 303",
    "city": "Valley Cottage",
    "state": "NY",
    "zipCode": "10989",
    "contactPerson": "",
    "vendorType": "service",
    "specialties": ["General Construction"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Pierson Building Centers",
    "email": "info@piersonbuilding.com",
    "phone": "(845) 469-2981",
    "address": "1979 Kings Hwy",
    "city": "Chester",
    "state": "NY",
    "zipCode": "10918",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Sherwin Williams",
    "email": "askSW@sherwin.com",
    "phone": "(845) 623-1420",
    "address": "106 Rockland Plaza",
    "city": "Nanuet",
    "state": "NY",
    "zipCode": "10954",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["Painting", "Coatings"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Standard Gypsum",
    "email": "info@standardgypsum.com",
    "phone": "(845) 357-2300",
    "address": "2 Blue Hill Plaza",
    "city": "Pearl River",
    "state": "NY",
    "zipCode": "10965",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["Drywall", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "The Home Depot Pro",
    "email": "prosupport@homedepot.com",
    "phone": "(845) 623-8715",
    "address": "240 W Route 59",
    "city": "Nanuet",
    "state": "NY",
    "zipCode": "10954",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Triangle Pacific Corp",
    "email": "info@trianglepacific.com",
    "phone": "(214) 887-5100",
    "address": "16803 Dallas Pkwy",
    "city": "Dallas",
    "state": "TX",
    "zipCode": "75248",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Ulster Building Supply",
    "email": "info@ulsterbuildingsupply.com",
    "phone": "(845) 338-0300",
    "address": "875 Broadway",
    "city": "Kingston",
    "state": "NY",
    "zipCode": "12401",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "United Rentals",
    "email": "customerservice@ur.com",
    "phone": "(845) 623-1500",
    "address": "70 W Nyack Rd",
    "city": "West Nyack",
    "state": "NY",
    "zipCode": "10994",
    "contactPerson": "",
    "vendorType": "service",
    "specialties": ["Equipment Rental"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "US LBM Holdings LLC",
    "email": "info@uslbm.com",
    "phone": "(215) 564-3600",
    "address": "1221 Locust St",
    "city": "Philadelphia",
    "state": "PA",
    "zipCode": "19107",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["Lumber", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Weyerhaeuser Company",
    "email": "info@weyerhaeuser.com",
    "phone": "(206) 539-3000",
    "address": "220 Occidental Ave S",
    "city": "Seattle",
    "state": "WA",
    "zipCode": "98104",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["Lumber", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "Wolff Bros Supply Inc",
    "email": "info@wolffbros.com",
    "phone": "(845) 856-5281",
    "address": "142 Plains Rd",
    "city": "New Paltz",
    "state": "NY",
    "zipCode": "12561",
    "contactPerson": "",
    "vendorType": "supplier",
    "specialties": ["General Supplies", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  },
  {
    "name": "84 Lumber Company",
    "email": "info@84lumber.com",
    "phone": "(724) 228-8820",
    "address": "1019 Route 519",
    "city": "Eighty Four",
    "state": "PA",
    "zipCode": "15330",
    "contactPerson": "Jennifer",
    "vendorType": "supplier",
    "specialties": ["Lumber", "Building Materials"],
    "paymentTerms": "Net 30",
    "isActive": true,
    "certifications": []
  }
];

export const importVendorsFromExcel = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if vendors already exist
    const existingVendors = await ctx.db.query("vendors").collect();
    if (existingVendors.length > 0) {
      return {
        success: false,
        message: `Vendors already exist in database (${existingVendors.length} vendors found). Skipping import.`,
        count: 0
      };
    }

    let importedCount = 0;
    let errorCount = 0;
    const errors: string[] = [];

    // Import each vendor
    for (const vendor of vendorData) {
      try {
        await ctx.db.insert("vendors", {
          name: vendor.name,
          email: vendor.email,
          phone: vendor.phone || undefined,
          address: vendor.address || undefined,
          city: vendor.city || undefined,
          state: vendor.state || undefined,
          zipCode: vendor.zipCode || undefined,
          contactPerson: vendor.contactPerson || undefined,
          vendorType: vendor.vendorType || undefined,
          specialties: vendor.specialties || undefined,
          certifications: vendor.certifications || undefined,
          paymentTerms: vendor.paymentTerms || undefined,
          isActive: vendor.isActive !== undefined ? vendor.isActive : true,
        });
        importedCount++;
      } catch (error) {
        errorCount++;
        errors.push(`Failed to import ${vendor.name}: ${error}`);
      }
    }

    return {
      success: true,
      message: `Successfully imported ${importedCount} vendors from Excel database.`,
      count: importedCount,
      errors: errorCount > 0 ? errors : undefined,
      errorCount
    };
  },
});
